Error Message,Possible Error Cause,Debugging
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type, possible: module (e.g. demandlib) not actual, upgrade module in the installation.cmd (pip install demandlib --upgrade)
HTTPSConnectionPool(host='pypi.python.org' port=443),A package named in the error message was not installed correctly due to a timeout, Reinstall the package manually in the virtual environment as follows: 1. open a terminal 2. navigate to your SESMG folder 3. navigate to the scripts-subfolder: ``cd Scripts``
